server:
  port: 8080
  servlet:
    context-path: /community

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: abc123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.163.com
    protocol: smtps
    username: dwj201717@163.com
    password: EAOCDOZKWFGRBTLH
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  #redis
  redis:
    database: 8
    host: localhost
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybbs.community.entity

#logging:
#  file:
#    name:
#      D:/developer/workplace_idea/community/log/community.log
#  level:
#    com.mybbs.community: debug
community:
  path:
    upload:
      D:/developer/workplace_idea/community/upload
#      D:/Download/data
    domain:
      http://localhost:8080




