server:
  port: 8080
  servlet:
    context-path: /community

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: abc123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.163.com
    protocol: smtps
    username: #
    password: #
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  #redis
  redis:
    database: 8
    host: localhost
    port: 6379

  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true  #是否自动提交消费者的的offset
      auto-commit-interval: 3000 # 毫秒    =3s
#  data:
#    elasticsearch:
#      cluster-name: mybbs
#      cluster-nodes: 127.0.0.1:9300
  elasticsearch:
    uris: 127.0.0.1:9200
  # TaskExecutionPorperties
  # ThreadPoolTaskScheduler
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
    scheduling:
      pool:
        size: 5
  # quartz   此处设置后，在第一次运行时读取此配置文件，然后写入db，以后不再读取此配置文件
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5




# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybbs.community.entity

#logging:
#  file:
#    name:
#      D:/developer/workplace_idea/community/log/community.log
#  level:
#    com.mybbs.community: debug
community:
  path:
    upload:
      D:/developer/workplace_idea/community/upload
#      D:/Download/data
    domain:
      http://localhost:8080


wk:
  image:
    command: D:/developer/wkhtmltopdf/bin/wkhtmltoimage
    storage: D:/developer/workplace_idea/community/data/wk-images


# caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180
